INSERT  INTO
	lh_exam_student
      ( 
      ID                            
      ,PHONE                          
      ,USERNAME                       
      ,PASSWORD                       
      ,STATUS                         
      ,OPENID                         
      ,SMSCODE                        
      ,USERKEY                        
      ,IDCARD                         
      ,REALNAME                       
      ,SEX                            
      ,ADDRESS                        
      ) 
values
      (
      :lhExamStudent.id                            
      ,:lhExamStudent.phone                         
      ,:lhExamStudent.username                      
      ,:lhExamStudent.password                      
      ,:lhExamStudent.status                        
      ,:lhExamStudent.openid                        
      ,:lhExamStudent.smscode                       
      ,:lhExamStudent.userkey                       
      ,:lhExamStudent.idcard                        
      ,:lhExamStudent.realname                      
      ,:lhExamStudent.sex                           
      ,:lhExamStudent.address                       
      )